node ('nodejs') {
   stage ('Checkout') {
      git branch: 'main',
          url: 'https://github.com/funkychicken1/DO400.git' 
   }
   stage ('Backend Tests') {
      sh 'node ./backend/test.js'
   }
   stage ('Frontend Tests') {
      sh 'node ./frontend/test.js'
   }
}
