pipeline {
   agent {
      node { 
         label 'nodejs' 
      }
      parameters {
         booleanParam(name: "RUN_FRONTEND_TESTS", defaultValue: true)
      }
   }
   stages {
      stage ('Checkout') {
         steps {
            git branch: 'main',
                url: 'https://github.com/funkychicken1/DO400.git' 
         } 
      }
      stage ('Run Tests') {
         parallel {
            stage ('Backend Tests') {
               steps {
                  sh 'node ./pipelines-control/backend/test.js'
               }
            }
            stage ('Frontend Tests') {
               steps {
                  sh 'node ./pipelines-control/frontend/test.js'
               }
            }
         }
      }
   }
}
